import { configDefaults, defineConfig } from 'vite-plus'

const omitBpeRankSourceMaps = {
  name: 'omit-bpe-rank-source-maps',
  generateBundle(
    _options: unknown,
    bundle: Record<
      string,
      { code?: string; map?: unknown; type: 'asset' | 'chunk' }
    >,
  ) {
    for (const [fileName, output] of Object.entries(bundle)) {
      if (output.type !== 'chunk' || !/^bpeRanks\/.*\.js$/.test(fileName)) {
        continue
      }

      output.code = output.code?.replace(
        /\n\/\/# sourceMappingURL=.*\.map\s*$/,
        '\n',
      )
      output.map = undefined
      delete bundle[`${fileName}.map`]
    }
  },
}

export default defineConfig({
  pack: {
    entry: [
      'src/**/*.{js,ts}',
      '!src/**/*.test.ts',
      '!src/codegen/**',
      '!src/scraper/**',
      '!src/**/*.gen.ts',
    ],
    cjsDefault: false,
    dts: true,
    outExtensions: () => ({ dts: '.d.ts', js: '.js' }),
    outputOptions: { exports: 'named' },
    platform: 'neutral',
    plugins: [omitBpeRankSourceMaps],
    root: 'src',
    sourcemap: true,
    target: 'es2022',
    unbundle: true,
  },
  test: {
    exclude: [
      ...configDefaults.exclude,
      'benchmark/*',
      'cjs/*',
      'esm/*',
      'dist/*',
    ],
  },
  lint: {
    plugins: ['oxc', 'typescript', 'unicorn', 'react'],
    categories: {
      correctness: 'error',
    },
    env: {
      builtin: true,
    },
    ignorePatterns: [
      '.yarn/**',
      'benchmark/**',
      'demo/**',
      'harmony/**',
      'src/bpeRanks/**',
      'src/chat/**',
      'src/model/**',
      'src/modelsChatEnabled.gen.ts',
    ],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-assignment': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'preserve-caught-error': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-array-constructor': 'error',
      'no-unused-expressions': 'error',
      'typescript/ban-ts-comment': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    overrides: [
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
        },
      },
      {
        files: ['src/**/*.{js,ts}'],
        rules: {
          'no-constant-condition': [
            'error',
            {
              checkLoops: false,
            },
          ],
          'no-useless-assignment': 'off',
          'no-unused-vars': 'off',
          'typescript/no-explicit-any': 'off',
          'typescript/no-empty-object-type': 'off',
          // Public methods are explicitly bound in GptEncoding's constructor.
          // Oxlint cannot infer that destructuring these methods is safe.
          'typescript/unbound-method': 'off',
        },
      },
    ],
    options: {
      reportUnusedDisableDirectives: 'error',
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
  },
  fmt: {
    arrowParens: 'always',
    bracketSpacing: true,
    semi: false,
    singleQuote: true,
    tabWidth: 2,
    trailingComma: 'all',
    printWidth: 80,
    sortPackageJson: false,
    ignorePatterns: [
      'node_modules/',
      'build/',
      'cjs/',
      'coverage/',
      'dist/',
      'dts/',
      'esm/',
      'lib/',
      'mjs/',
      'umd/',
      'benchmark/',
      'demo/',
      'harmony/',
      'temp.local/',
      '**/*.gen.ts',
      'src/bpeRanks/',
      'src/chat/',
      'src/model/',
      'src/models.ts',
    ],
  },
})
