// This file was generated by src/codegen/generateByModel.ts.
// To regenerate, run: yarn codegen:models.
// Source template: src/encoding/o200k_base.ts.

import bpeRanks from '../bpeRanks/o200k_base.js'
import { GptEncoding } from '../GptEncoding.js'

export * from '../constants.js'
export * from '../specialTokens.js'
// oxfmt-ignore
const api = GptEncoding.getEncodingApiForModel('chat-latest', () => bpeRanks, {name:"chat-latest",slug:"chat-latest",performance:3,latency:3,modalities:{input:["text","image"],output:["text"]},supported_endpoints:["responses","chat_completions"],supported_features:["structured_outputs","function_calling","streaming","image_input"],context_window:400000,max_output_tokens:128000,max_input_tokens:272000,knowledge_cutoff:new Date(1756598400000),reasoning_tokens:false})
const {
  decode,
  decodeAsyncGenerator,
  decodeGenerator,
  encode,
  encodeGenerator,
  isWithinTokenLimit,
  countTokens,
  encodeChat,
  countChatCompletionTokens,
  encodeChatGenerator,
  vocabularySize,
  setMergeCacheSize,
  clearMergeCache,
  estimateCost,
} = api
export {
  clearMergeCache,
  countTokens,
  decode,
  decodeAsyncGenerator,
  decodeGenerator,
  encode,
  encodeChat,
  countChatCompletionTokens,
  encodeChatGenerator,
  encodeGenerator,
  estimateCost,
  isWithinTokenLimit,
  setMergeCacheSize,
  vocabularySize,
}
export default api
