// This file was generated by src/codegen/generateByModel.ts.
// To regenerate, run: yarn codegen:models.
// Source template: src/encoding/gpt2.ts.

export { default } from '../encoding/gpt2.js'
export * from '../encoding/gpt2.js'
