// eslint-disable-next-line no-restricted-exports, import/no-default-export
// This file was generated by src/codegen/generateByModel.ts.
// To regenerate, run: yarn codegen:models.
// Source template: src/encoding/o200k_base.ts.

export { default } from '../encoding/o200k_base.js'
export * from '../encoding/o200k_base.js'
