/* eslint-disable import/extensions */
// This file was generated by src/codegen/generateByModel.ts.
// To regenerate, run: yarn codegen:models.
// Source template: src/encoding/o200k_harmony.ts.

import bpeRanks from '../bpeRanks/o200k_base.js'
import { GptEncoding } from '../GptEncoding.js'

export * from '../constants.js'
export * from '../specialTokens.js'
// prettier-ignore
const api = GptEncoding.getEncodingApiForModel('gpt-oss-20b', () => bpeRanks, {name:"gpt-oss-20b",slug:"gpt-oss-20b",performance:4,latency:3,modalities:{input:["text"],output:["text"]},context_window:131072,max_output_tokens:131072,knowledge_cutoff:new Date(1717200000000),supported_features:["streaming","structured_outputs","function_calling"],supported_endpoints:["responses","batch"],reasoning_tokens:true,price_data:{main:{input:.0002,cached_output:.00005,output:.0006},batch:{input:.00015,output:.0005}}})
const {
  decode,
  decodeAsyncGenerator,
  decodeGenerator,
  encode,
  encodeGenerator,
  isWithinTokenLimit,
  countTokens,
  encodeChat,
  countChatCompletionTokens,
  encodeChatGenerator,
  vocabularySize,
  setMergeCacheSize,
  clearMergeCache,
  estimateCost,
} = api
export {
  clearMergeCache,
  countTokens,
  decode,
  decodeAsyncGenerator,
  decodeGenerator,
  encode,
  encodeChat,
  countChatCompletionTokens,
  encodeChatGenerator,
  encodeGenerator,
  estimateCost,
  isWithinTokenLimit,
  setMergeCacheSize,
  vocabularySize,
}
// eslint-disable-next-line import/no-default-export
export default api
