export const EndOfText = '<|endoftext|>'
export const FimPrefix = '<|fim_prefix|>'
export const FimMiddle = '<|fim_middle|>'
export const FimSuffix = '<|fim_suffix|>'
export const EndOfPrompt = '<|endofprompt|>'
